name: Swift

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      
  run-tests:
    runs-on:  macOS-latest
    steps:
      - name: Run tests
        run: swift test -v
